### ISSUE TITLE
source code request

### ISSUE THREAD

**Issue by xiaofeixia2022** [zipengxuc/StylerDALLE#2]
I saw your article on arxiv, and I think your work is excellent with very impressive results. I would like to know how the model was implemented. Could you please let me know when your work will be open-sourced, or you can contact me at [y80220078@mail.ecust.edu.cn](mailto:y80220078@mail.ecust.edu.cn). Thank you very much!

**Comment by zipengxuc** [comment]
Hello, thank you for your attention. Our code will be released in a few days. Please stay tuned. :)
