### ISSUE TITLE
Thanks for your excellent work

### ISSUE THREAD

**Issue by shehuiyaoa11y** [zipengxuc/StylerDALLE#4]
Thanks for your excellent work, I really like the code of this paper, using very few libraries,  which is very nice. I would like to use style transfer work for road segmentation. Thank you for the code in this paper.
can you please give me the test code?

PS: StylerDALLE is great!

**Comment by zipengxuc** [comment]
Hello, thank you! I will update the test code very soon and let you know by then.

**Comment by zipengxuc** [comment]
Hi, thank you! The code is uploaded, please check it out.
