### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xff'.

### ISSUE THREAD

**Issue by ZYDeeplearning** [zipengxuc/StylerDALLE#5]
May I ask why running python train.py gives this error when training in the first stage? _pickle.UnpicklingError: invalid load key, '\xff'. Pre-trained models are loaded

**Comment by zipengxuc** [comment]
Hi, I've never met this error before but I googled for your problem. Can you check if the checkpoints of pretrained models were downloaded properly?
Please refer to these links: [link#1](https://github.com/lukemelas/EfficientNet-PyTorch/issues/160), [link#2](https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key).

**Comment by ZYDeeplearning** [comment]
> 嗨，我以前从未遇到过这个错误，但我用谷歌搜索了你的问题。你能检查预训练模型的检查点是否正确下载吗？请参阅以下链接：链接#[1、链接#](https://github.com/lukemelas/EfficientNet-PyTorch/issues/160)[2](https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key)。

Here is mainly when using the torch.load function to load the dataset when the error is reported, I read your related link, but it can't be solved, will this problem be the cause of windows? Thank you!
![image](https://github.com/zipengxuc/StylerDALLE/assets/107866293/ff0c0844-0a27-4cca-8bec-9f45bb848d06)

**Comment by zipengxuc** [comment]
did you preprocess the data?

**Comment by ZYDeeplearning** [comment]
Thanks for the reminder, I performed python prep/prep_coco.py processing, but there is no saved XX.pt file after running, as shown in the figure below, excuse me, is this the reason? thank you again!
![image](https://github.com/zipengxuc/StylerDALLE/assets/107866293/8f9c784f-b769-4838-a4a9-ddcb04cc18b2)
![image](https://github.com/zipengxuc/StylerDALLE/assets/107866293/fd247a09-375d-4b5c-b4a9-b4f7aac21a0a)

**Comment by zipengxuc** [comment]
probably you could check if you set the 'out_data_path' correctly
